# Example values file demonstrating Swagger UI configuration
# This example shows how to deploy the chart with Swagger UI enabled and exposed via ingress

replicaCount: 1

image:
  repository: ghcr.io/chatwoot-br/go-whatsapp-web-multidevice
  pullPolicy: IfNotPresent
  tag: "latest"

# Admin API configuration
admin:
  port: 8088
  token: "your-admin-token-here"  # Change this to a secure token

# Service configuration
service:
  type: ClusterIP
  ports:
    # Admin API port
    - name: admin-api
      port: 8088
      targetPort: 8088
      protocol: TCP
    # Swagger UI port
    - name: swagger-ui
      port: 8080
      targetPort: 8080
      protocol: TCP
    # Supervisord RPC port
    - name: supervisor-rpc
      port: 9001
      targetPort: 9001
      protocol: TCP
    # WhatsApp instance ports (3001-3010)
    - name: whatsapp-3001
      port: 3001
      targetPort: 3001
      protocol: TCP
    - name: whatsapp-3002
      port: 3002
      targetPort: 3002
      protocol: TCP
    - name: whatsapp-3003
      port: 3003
      targetPort: 3003
      protocol: TCP
    - name: whatsapp-3004
      port: 3004
      targetPort: 3004
      protocol: TCP
    - name: whatsapp-3005
      port: 3005
      targetPort: 3005
      protocol: TCP
    - name: whatsapp-3006
      port: 3006
      targetPort: 3006
      protocol: TCP
    - name: whatsapp-3007
      port: 3007
      targetPort: 3007
      protocol: TCP
    - name: whatsapp-3008
      port: 3008
      targetPort: 3008
      protocol: TCP
    - name: whatsapp-3009
      port: 3009
      targetPort: 3009
      protocol: TCP
    - name: whatsapp-3010
      port: 3010
      targetPort: 3010
      protocol: TCP

# Ingress configuration (expose both Admin API and Swagger UI)
ingress:
  enabled: true
  className: "nginx"  # or your ingress class
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Optional: Add basic auth for the admin endpoints
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: admin-auth
  hosts:
    - host: whatsapp-admin.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: whatsapp-admin-tls
      hosts:
        - whatsapp-admin.yourdomain.com

# Swagger UI configuration
swaggerUI:
  enabled: true
  image:
    repository: swaggerapi/swagger-ui
    tag: "latest"
    pullPolicy: IfNotPresent
  port: 8080
  config:
    # Swagger UI customization
    deepLinking: true
    displayOperationId: false
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    defaultModelRendering: "example"
    displayRequestDuration: true
    docExpansion: "list"
    filter: false
    maxDisplayedTags: -1
    showExtensions: false
    showCommonExtensions: false
    tagsSorter: "alpha"
    validatorUrl: null

# Persistence configuration
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

# Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Probes configuration
livenessProbe:
  httpGet:
    path: /healthz
    port: admin-api
  initialDelaySeconds: 40
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /readyz
    port: admin-api
  initialDelaySeconds: 35
  periodSeconds: 5
  timeoutSeconds: 3

startupProbe:
  httpGet:
    path: /healthz
    port: admin-api
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 12

# Environment variables
env:
  - name: SUPERVISOR_URL
    value: "http://127.0.0.1:9001/RPC2"
  - name: SUPERVISOR_USER
    value: "admin"
  - name: SUPERVISOR_PASS
    value: "admin123"
  - name: SUPERVISOR_CONF_DIR
    value: "/etc/supervisor/conf.d"
  - name: INSTANCES_DIR
    value: "/app/instances"
  - name: SUPERVISOR_LOG_DIR
    value: "/var/log/supervisor"
  - name: LOCK_DIR
    value: "/tmp"
  - name: DB_URI
    value: "file:/app/storages/whatsapp.db?_foreign_keys=on"
  - name: APP_DEBUG
    value: "true"
  - name: WHATSAPP_CHAT_STORAGE
    value: "true"
  - name: ADMIN_PORT
    value: "8088"
  - name: ADMIN_DEBUG
    value: "true"
  - name: WHATSAPP_SETTING_MAX_AUDIO_SIZE
    value: "16777216"
  - name: WHATSAPP_SETTING_AUTO_CONVERT_AUDIO
    value: "true"

# Volume mounts
volumeMounts:
  - mountPath: /etc/supervisor/supervisord.conf
    name: supervisor-config
    readOnly: true
    subPath: supervisord.conf
  - mountPath: /etc/supervisor/conf.d
    name: shared-data
    subPath: supervisor/conf.d
  - mountPath: /app/instances
    name: shared-data
    subPath: instances
  - mountPath: /var/log/supervisor
    name: shared-data
    subPath: supervisor/logs
  - mountPath: /var/run
    name: supervisor-run
  - mountPath: /app/statics
    name: shared-data
    subPath: statics
  - mountPath: /app/storages
    name: shared-data
    subPath: storages
  - mountPath: /tmp
    name: app-temp

# Enable volumes
volumes: true
